---
workflow:
  name: Linting
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

default:
  image: python:3.11.5-bullseye
  tags:
    - graphiant-default

stages:
  - lint

flake8:
  stage: lint
  script:
    - pip install flake8
    - flake8 ./libs
    - flake8 ./test

pylint:
  stage: lint
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  image: python:3.11.5-bullseye
  cache:
    paths:
      - .cache/pip/
      - venv/
      - .pylint_cache/
  script:
    - python3.11 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pylint --errors-only ./libs

jinjalint:
  stage: lint
  script:
    - python3.11 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - djlint configs -e yaml
    - djlint templates -e yaml
