global_prefix_sets: 
  - name: canva_prod_prefix_list_1
    description: For_testing_canva_prod_prefix_list_1
    mode: ipv4
    entries:
      - idx: 1
        ip_prefix: 1.1.1.0/24
        rule: exact
        prefix_length: 24
      - idx: 2
        ip_prefix: 1.2.1.0/24
        rule: range
        from_prefix: 24
        to_prefix: 32
      - idx: 3
        ip_prefix: 1.3.0.0/16
        rule: less_and_equal
        prefix_length: 24
      - idx: 4
        ip_prefix: 1.4.1.0/24
        rule: greater_and_equal
        prefix_length: 24
  - name: canva_prod_prefix_list_2
    description: For_testing_canva_prod_prefix_list_2
    mode: ipv4
    entries:
      - idx: 1
        ip_prefix: 10.1.1.0/24
        rule: exact
        prefix_length: 24
      - idx: 2
        ip_prefix: 10.2.1.0/24
        rule: range
        from_prefix: 24
        to_prefix: 32
      - idx: 3
        ip_prefix: 10.3.0.0/16
        rule: less_and_equal
        prefix_length: 24
      - idx: 4
        ip_prefix: 10.4.1.0/24
        rule: greater_and_equal
        prefix_length: 24

routing_policies:
  - name: canva_bgp_inbound_filter
    direction: inbound
    implicit_rule: Accept
    policy_statements:
      - sequence_number: 10
        match_prefix_list: canva_prod_prefix_list_1
        action_permit: accept
        action_set_local_preference: 100
      - sequence_number: 20
        match_community:
          - 65000:1001
        action_permit: accept
        action_set_local_preference: 200
  - name: canva_bgp_outbound_filter
    direction: outbound
    implicit_rule: Accept
    policy_statements:
      - sequence_number: 10
        match_prefix_list: canva_prod_prefix_list_2
        action_permit: accept
        action_set_local_preference: 300
      - sequence_number: 20
        match_community:
          - 65000:1002
        action_permit: accept
        action_set_local_preference: 400