edge-1-canva:
  wan:
    - interface_name: GigabitEthernet5/0/0
      circuit_name: c-gigabitethernet5-0-0
      ipv4_dhcp: true
  lan:
    - interface_name: GigabitEthernet8/0/0
      ipv4_address: 10.1.7.1/24
      ipv6_address: 2001:10:1:7::1/64
      lan: lan-71-canva
      vlan: 18
edge-2-canva:
  wan:
    - interface_name: GigabitEthernet5/0/0
      circuit_name: c-gigabitethernet5-0-0
      ipv4_address: 100.200.1.1/24
  lan:
    - interface_name: GigabitEthernet8/0/0
      ipv4_address: 10.1.7.2/24
      ipv6_address: 2001:10:1:7::2/64
      lan: lan-7-canva
edge-3-canva:
  wan:
    - interface_name: GigabitEthernet5/0/0
      circuit_name: c-gigabitethernet5-0-0
      ipv4_address: 100.200.2.1/24
  lan:
    - interface_name: GigabitEthernet8/0/0
      ipv4_address: 10.1.7.3/24
      ipv6_address: 2001:10:1:7::3/64
      lan: lan-7-canva
      vlan: 28
