interfaces:
  - edge-1-sdktest:
    # WAN Interface with IPv4/IPv6 DHCP enabled
    - interface_name: GigabitEthernet5/0/0
      circuit: c-gigabitethernet5-0-0
      description: wan_1
      alias: primary_wan
    # VLAN Sub-Interface with Static IP assignment
    - interface_name: GigabitEthernet8/0/0
      sub_interfaces:
        - vlan: 18
          lan: lan-7-test
          ipv4_address: 10.2.7.1/24
          ipv6_address: 2001:10:2:7::1/64
          description: lan-7
          alias: non_production
  - edge-2-sdktest:
    # WAN Interface with Static IPv4 and DHCP IPv6 assignment and not enabling it
    - interface_name: GigabitEthernet5/0/0
      circuit: c-gigabitethernet5-0-0
      ipv4_address: 100.200.1.1/24
      admin_status: False
    # Multiple VLAN SUB-Interfaces with Static IPv4/IPv6 assignments
    - interface_name: GigabitEthernet8/0/0
      sub_interfaces:
        - vlan: 28
          lan: lan-7-test
          ipv4_address: 10.2.7.2/24
          ipv6_address: 2001:10:2:7::2/64
          description: lan-7
          alias: non_production
        - vlan: 29
          lan: lan-8-test
          ipv4_address: 10.2.8.2/24
          ipv6_address: 2001:10:2:8::2/64
          description: lan-8
          alias: production
