bgp_peering:
  - edge-1-keshav:
      route_policies:
        - test_bgp_inbound_filter
        - test_bgp_outbound_filter
      segments:
        - lan_segment: lan-7-keshav
          local_ipv4_address: 10.2.7.1
          local_interface: GigabitEthernet8/0/0.18
          neighbors:
            - remote_ipv4_address: 10.2.7.11
              peer_as: 60011
              ipv4_inbound_filter: test_bgp_inbound_filter
              ipv4_outbound_filter: test_bgp_outbound_filter
  - edge-2-keshav:
      route_policies:
        - test_bgp_inbound_filter
        - test_bgp_outbound_filter
      segments:
        - lan_segment: lan-7-keshav
          local_ipv4_address: 10.2.7.2
          local_interface: GigabitEthernet8/0/0.28
          neighbors:
            - remote_ipv4_address: 10.2.7.12
              peer_as: 60021
              ipv4_inbound_filter: test_bgp_inbound_filter
              ipv4_outbound_filter: test_bgp_outbound_filter
  - edge-3-keshav:
      route_policies:
        - test_bgp_inbound_filter
        - test_bgp_outbound_filter
      segments:
        - lan_segment: lan-7-keshav
          local_ipv4_address: 10.2.7.3
          local_interface: GigabitEthernet8/0/0.28
          neighbors:
            - remote_ipv4_address: 10.2.7.13
              peer_as: 60031
              ipv4_inbound_filter: test_bgp_inbound_filter
              ipv4_outbound_filter: test_bgp_outbound_filter
