snmps:
  # Global SNMP Service Configuration - SNMPv3 NoAuthNoPriv
  - name: snmp-global-test-noauth
    v3Enabled: true
    engineEndpoints:
      - lanSegment: lan-7-test
    usmLocalUsers:
      - name: v3_noauth
    vacmGroups:
        accesses:
          - name: snmpV3Access_noauth
            securityLevel: SnmpSecurityNoAuthNoPriv

  # Global SNMP Service Configuration - SNMPv3 AuthNoPriv
  - name: snmp-global-test-authnopriv
    v3Enabled: true
    engineEndpoints:
      - lanSegment: lan-7-test
    usmLocalUsers:
      - name: v3_auth
        authProtocol: SnmLocalAuthMd5
        authPassphrase: testing@123!
    vacmGroups:
        accesses:
          - name: snmpV3Access_auth
            securityLevel: SnmpSecurityAuthNoPriv

  # Global SNMP Service Configuration - SNMPv3 AuthPriv
  - name: snmp-global-test-authpriv
    v3Enabled: true
    engineEndpoints:
      - lanSegment: lan-7-test
    usmLocalUsers:
      - name: v3_authpriv
        authProtocol: SnmLocalAuthMd5
        authPassphrase: testing@123!
        encryptionProtocol: SnmpLocalEncryptDes
        encryptionPassphrase: systest@graphiant
    vacmGroups:
        accesses:
          - name: snmpV3Access_authpriv
            securityLevel: SnmpSecurityAuthPriv

  # Global SNMP Service Configuration - SNMPv2c
  - name: snmp-global-test-v2c
    v2cEnabled: true
    engineEndpoints:
      - lanSegment: lan-7-test
    communities:
      - communityString: public
    vacmGroups:

syslogServers:
  # Global Syslog Server Configuration
  - name: syslog-global-test
    target:
      host: 10.1.7.2
      port: 443
      transport: tcp
      severity: alert
      lanSegment: lan-7-test
      serverStatus: true

ipfixExporters:
  # Global IPFIX Exporter Configuration
  - name: ipfix-global-test
    exporter:
      destinationAddress: 10.1.7.2
      destinationPort: 70
      monitoredSegments:
        - lan-7-test
        - lan-8-test
      lanSegment: lan-7-test
      sampleMode: random
      sampleRate: 100

vpnProfiles:
  # Global VPN Profile Configuration
  - name: vpnprofile-global-test
    vpnProfile:
      ikeEncryptionAlg: AES 128 GCM
      ikeDhGroup: Group 19
      ikeIntegrity: SHA384
      reauthInterval: 3600
      ipsecEncryptionAlg: AES 256 CBC
      perfectForwardSecrecy: Group 20
      ipsecIntegrity: SHA256
      rekeyInterval: 3600
      antiReplayWindowSize: 64
      esn: false
      dpdInterval: 30
