---
- name: Configuring interfaces for Edge Devices from Input YAML
  hosts: localhost
  gather_facts: false

  # Option #1 - Variables can be inventory file as host, group or all hosts variables.
  # Option #2 - Variables from var files and can be included in plabook/role using vars_file or include_vars directive.
  # Option #3 - Variables inside playbook/role using vars directive.
  # Option #4 - Variables can be passed in runtime using --extra_vars or -e (Higher precedence) 
  #             key=value format (or)J SON string format (or) JSON or Yaml file  --extra-vars=@vars/credentials.yml)
  # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence

  vars:
    portal_url: https://api.test.graphiant.io
    portal_username: None
    portal_password: None

    gcs_client_params: &gcs_client_params
      portal_url: "{{ portal_url }}"
      password: "{{ portal_password }}"
      username: "{{ portal_username }}"


  tasks:
    - name: Configuring Graphiant Edge interfaces
      graphiant.portal.graphiant_interfaces:
        <<: *gcs_client_params
        input_config_yaml: edge_configs.yaml
        action: deconfig
        device_type: edge
      register: request_results
