---
workflow:
  name: Linting
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

default:
  image: python:3.12-slim
  tags:
    - graphiant-default

stages:
  - lint

jinjalint:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - djlint ansible_collections/graphiant/graphiant_playbooks/configs -e yaml
    - djlint ansible_collections/graphiant/graphiant_playbooks/templates -e yaml

ansible-lint:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - ansible-galaxy collection install ansible_collections/graphiant/graphiant_playbooks/ --force
    - ansible-lint --config-file ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/.ansible-lint ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/playbooks/

lint-collection-docs:
  stage: lint
  script:
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - ansible-galaxy collection install ansible_collections/graphiant/graphiant_playbooks/ --force
    - antsibull-docs lint-collection-docs --plugin-docs ~/.ansible/collections/ansible_collections/graphiant/graphiant_playbooks/

ansible-test-sanity:
  stage: lint
  parallel:
    matrix:
      - ANSIBLE_CORE: ["2.17", "2.18", "2.19"]
  script:
    - apt-get update && apt-get install -y git
    - python3.12 -m venv venv
    - source venv/bin/activate
    - pip3 install --upgrade pip
    - pip3 install ansible-core~=${ANSIBLE_CORE}
    - pip3 install -r ansible_collections/graphiant/graphiant_playbooks/requirements.txt
    - cd ansible_collections/graphiant/graphiant_playbooks
    - ansible-test sanity --color --python 3.12 --exclude templates/ --exclude configs/de_workflows_configs/